"""add is_admin to users

Revision ID: 567f7fb5bb35
Revises: 7464be83df4f
Create Date: 2026-08-15 14:41:11.217856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567f7fb5bb35'
down_revision = '7464be83df4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
